# -*- coding: utf-8 -*-
"""Priyanka_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K9y-fbfzmsqXoG8EiWt06Bx3nqgsCWgL

Task 1: Exploratory Data Analysis (EDA) and Business Insights

1. Loading and Inspecting Data
"""

import numpy as num
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

#uploading dataset
customers= pd.read_csv("/content/Customers.csv")
products = pd.read_csv("/content/Products.csv")
transactions = pd.read_csv("/content/Transactions.csv")

#basic info of customers
print(customers.info(), "\n")
print(customers.describe(include='all'), "\n")

#basic info of products
print(products.info(), "\n")
print(products.describe(include='all'), "\n")

#basic info of transactions
print(transactions.info(),"\n")
print(transactions.describe(include='all'), "\n")

"""2. Data Cleaning"""

# Remove duplicates from customers
customers = customers.drop_duplicates()
print(customers.info())

#Remove duplicates from products
products = products.drop_duplicates()
print(products.info())

#Remove duplocates from transaction
transactions = transactions.drop_duplicates()
print(transactions.info())

#Check for null values customers
print(customers.isnull().sum())

# Check for null values of production
print(products.isnull().sum())

# Check for null values of transaction
print(customers.isnull().sum())

# Validate numeric columns
print(transactions[transactions['Quantity'] < 0])  # Negative quantities
print(transactions[transactions['Price'] < 0])    # Negative prices
print(products[products['Price'] < 0]) # Negative product prices

"""3. Data Relationships and Merging"""

# Merge transactions with customers
merged_data = transactions.merge(customers, on='CustomerID', how='left')

# Merge with products
merged_data = merged_data.merge(products, on='ProductID', how='left')

# Check the resulting dataset
print(merged_data.head())

"""4. Exploratory Analysis
*   Number of customers by region.
*   Monthly/Yearly sign-up trends.







"""

# Customers by region
region_counts = customers['Region'].value_counts()
region_counts.plot(kind='bar', title='Customers by Region')
plt.show()

# Signup trends
customers['SignupDate'] = pd.to_datetime(customers['SignupDate'])
customers['SignupMonth'] = customers['SignupDate'].dt.to_period('M')
signup_trends = customers['SignupMonth'].value_counts().sort_index()

signup_trends.plot(kind='line', title='Signup Trends Over Time')
plt.show()

"""B. Products
*   Count and distribution by category.
*   Price distribution.



"""

# Products by category
category_counts = products['Category'].value_counts()
category_counts.plot(kind='bar', title='Products by Category')
plt.show()

# Price distribution
sns.histplot(products['Price'], bins=20, kde=True)
plt.title('Price Distribution')
plt.show()

"""C. Transactions
*   Monthly transaction trends.
*  Top products by sales volume and revenue.
*   Top customers by revenue.








"""

# Monthly transaction trends
transactions['TransactionDate'] = pd.to_datetime(transactions['TransactionDate'])
transactions['TransactionMonth'] = transactions['TransactionDate'].dt.to_period('M')
monthly_sales = transactions.groupby('TransactionMonth')['TotalValue'].sum()

monthly_sales.plot(kind='line', title='Monthly Sales Trends')
plt.show()

# Top products by sales volume
top_products = merged_data.groupby('ProductName')['Quantity'].sum().sort_values(ascending=False).head(10)
top_products.plot(kind='bar', title='Top Products by Sales Volume')
plt.show()

# Top customers by revenue
top_customers = merged_data.groupby('CustomerName')['TotalValue'].sum().sort_values(ascending=False).head(10)
top_customers.plot(kind='bar', title='Top Customers by Revenue')
plt.show()

"""Here are five business insights derived from the EDA:

* Customer Distribution: Certain regions have significantly higher customer counts, suggesting potential markets for focused marketing and expansion.
* Customer Signup Trends: Peak signup periods can be used to predict customer acquisition trends and allocate resources during those times.
* Popular Product Categories: Some product categories dominate sales, indicating areas for increased investment or promotion.
* Seasonal Sales Patterns: Monthly sales trends reveal seasonal spikes, which can guide inventory planning and marketing campaigns.
* Top Customers' Contribution: Identifying high-revenue customers allows for personalized strategies to increase retention and revenue generation.

"""